name: Build and Publish to GHCR

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Login ke GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/tools:latest .

    - name: Push ke GHCR
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/tools:latest
